#
# Module manifest for module 'monkey365'
#
# Generated by: Juan Garrido
#
# Generated on: 4/7/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'monkey365.psm1'

# Version number of this module.
ModuleVersion = '0.95.5'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'b040dfab-f762-4ce1-bcc4-1b3963603ff1'

# Author of this module
Author = 'Juan Garrido'

# Company or vendor of this module
CompanyName = 'monkey365'

# Copyright statement for this module
Copyright = '(c)2021 Juan Garrido. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Monkey365 provides a tool for security consultants to easily conduct not only Microsoft 365, but also Azure subscriptions and Azure Active Directory security configuration reviews.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    #'core/modules/monkeyutils/monkeyutils.psm1',
    #'core/modules/monkeylogger/monkeylogger.psm1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Invoke-Monkey365',
    'Get-MonkeyJobError'
    'Convert-MarkDownToHtml',
    'Convert-MarkDownToPlainText',
    'Copy-PsObject',
    'ConvertTo-SecureScriptBlock',
    'Update-PsObject',
    'Get-AstFunction',
    'Get-ObjectPropertyByPath'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            "Microsoft365",
            "Microsoft365-Security",
            "Azure",
            "AzureAD",
            "EntraID-Security-Assessment",
            "Microsoft-Entra",
            "Cloud-Security-Configuration-Review",
            "CSPM",
            "Office365",
            "Office-365-Security",
            "CIS-Benchmark"
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/silverhack/monkey365/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://silverhack.github.io/monkey365/'

        # A URL to an icon representing this module.
        IconUri = 'https://user-images.githubusercontent.com/5271640/181045413-1d17333c-0533-404a-91be-2070ccc6ee29.png'

        #Prerelease = 'beta'

        # ReleaseNotes of this module
        ReleaseNotes = '*'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://silverhack.github.io/monkey365/'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


