ConvertFrom-StringData @'
    UnableToGetRules                 = No rules were loaded
    InitDataset                      = Dataset was created
    DatasetNotCreated                = Dataset was not created
    InvalidObject                    = Unable to query dataset. Invalid Object.
    UnableToCloneObject              = Unable to clone object
    DirectoryFoundMessage            = {0} directory was found in {1}
    AdditionalRulesMessage           = Importing additional rules from {0}
    UnableToSetRuleset               = Unable to set ruleset
    RulesetNotLoaded                 = The ruleset was not loaded
    UnableToGetRulesetInfo           = Unable to get information from ruleset
    UnableToGetMetadataInfo          = Unable to get metadata info from '{0}'
    UnableToRemoveVars               = Unable to remove vars
    UnableToInitializeVars           = Unable to initialize vars
    UnableToInitializeRuleset        = Unable to initialize ruleset
    UnableToGetObjectProperty        = Unable to get '{0}' property from object
    FileNotFound                     = File {0} was not found in {1}
    FileNotFoundGenericMessage       = File {0} was not found
    DuplicateFileFound               = Duplicate file {0} was found in {1}
    InvalidRuleMessage               = The rule '{0}' is not valid
    IncludeObjectErrorMessage        = Include file present in '{0}' is not valid
    ValidObjectMessage               = The {0} is valid
    MissingElementsMessage           = The {0} is not valid. The following properties were not found: {1} 
    LevelNotSet                      = Level was not set for {0}. Setting INFO level
    UnableToGetConditionsFile        = Unable to get conditions file from {0}
    UnableToParseFilter              = Unable to parse filter for {0}
    UnableToGetNestedFilter          = Unable to get nested filter
    InvalidCondition                 = The {0} condition is not valid
    InvalidQueryGenericMessage       = Invalid query found in "{0}"
    StatementErrorMessage            = Wrong statement. The '{0}' operator within the '{1}' condition is not recognized as a valid operator
    ConditionErrorMessage            = Unable to get conditions
    OperatorNotFoundErrorMessage     = Invalid query. Logical operator was not found
    BuildQueryMessage                = Building query for {0}
    ConditionErrorGenericMessage     = Unable to resolve condition
    BuildQueryErrorMessage           = Unable to build query for {0}
    BuildQueryGenericErrorMessage    = Unable to build query
    UnrecognizedFilter               = Unable to create filter. Invalid filter
    ElementNotFound                  = Unable to find element {0} on object
    UpdatingComlianceMessage         = Updating compliance for {0} rule
    FailedQueryMessage               = The "{0}" query failed to complete its execution on "{1}" rule
    UnitItemNotFound                 = Removing rules for "{0}" as it was not found on dataset
    FalsePositiveDetected            = Potentially false positive detected on "{0}"
    MethodNotFound                   = GetPropertyByPath method was not loaded
    EmptyRuleGenericMessage          = Empty rule found in "{0}"
    PathNotFoundErrorMessage         = "{0}" was not found in dataset
    UnableToFormatErrorMessage       = Unable to format {0} data
'@