ConvertFrom-StringData @'
    UnableToConvertToScriptBlock     = Unable to convert {0} to a valid ScriptBlock
    UnableToGetRules                 = No rules were loaded
    InitDataset                      = Dataset was created
    InvalidObject                    = Unable to query dataset. Invalid Object.
    UnableToCloneObject              = Unable to clone object
    DirectoryFoundMessage            = {0} directory was found in {1}
    AdditionalRulesMessage           = Importing additional rules from {0}
    UnableToSetRuleset               = Unable to set ruleset
    RulesetNotLoaded                 = The ruleset was not loaded
    UnableToGetRulesetInfo           = Unable to get information from ruleset
    UnableToRemoveVars               = Unable to remove vars
    UnableToInitializeVars           = Unable to initialize vars
    UnableToInitializeRuleset        = Unable to initialize ruleset
    UnableToGetObjectProperty        = Unable to get property 'File' from object
    FileNotFound                     = File {0} was not found in {1}
    DuplicateFileFound               = Duplicate file {0} was found in {1}
    InvalidRuleMessage               = The {0} is not valid
    ValidObjectMessage               = The {0} is valid
    MissingElementsMessage           = The {0} is not valid. Missing {1}
    LevelNotSet                      = Level was not set for {0}. Setting INFO level
    UnableToGetConditionsFile        = Unable to get conditions file from {0}
    UnableToParseFilter              = Unable to parse filter for {0}
    UnableToGetNestedFilter          = Unable to get nested filter
    InvalidCondition                 = The {0} condition is not valid
    BuildQueryMessage                = Building query for {0}
    BuildQueryErrorMessage           = Unable to build query for {0}
    ElementNotFound                  = Unable to find element {0} on object
    UpdatingComlianceMessage         = Updating compliance for {0} rule
    UpdatingPropertyMessage          = Updating {0} for {1} rule
    FailedQueryMessage               = The "{0}" query failed to complete its execution on "{1}" rule
    UnitItemNotFound                 = Removing rules for "{0}" as it was not found on dataset
    FalsePositiveDetected            = Potentially false positive detected on "{0}"
'@