# en-US
ConvertFrom-StringData @'
SuccessfullyConnected            = Successfully connected to Resource Management API
AdalUnsupportedOSErrorMessage    = Use of ADAL library is not supported on PowerShell core on {0}. Importing MSAL library
MSALGenericLibraryLoadMessage    = Loading MSAL authentication library
AADTenantInfoMessage             = Getting tenant information from {0} Id
AADUserErrorMessage              = Unable to set UserPrincipalName
AADEmptyTenantMessage            = Found empty tenantId in local settings. Setting TenantID to {0}
O365TenantInfoError              = Unable to get information from Tenant
RBACUserInfoError                = Unable to get RBAC information for {0}
AADRMServiceLocatorError         = Unable to resolve AADRM service locator
LyncDomainNotResolved            = The Lync discover domain could not be resolved
LyncFederatedDomainNotFound      = No federated domain was found on {0}
O365ATPInfoError                 = Unable to get O365 Advanced Threat Protection Info
O365LicenseInfoError             = Unable to get friendly name of O365 licenses
MonkeyProfileLoadError           = Unable to load profile
MonkeyParametersGenericError     = Unable to get parameters
MonkeyDefaultParametersLoad      = Loading default profile
MonkeyWrongParametersFound       = Wrong parameters were found: {0}
MonkeyProfileNotExists           = {0} does not exists
UnableToGetPlugins               = Unable to get plugins for {0}
TimeElapsedScript                = Total time for JOBs: {0} Minutes
UnableToCreateRunspacePool       = Unable to create runspace pool. Empty plugins loaded
TimeSpentInvokeBatchMessage      = Time spent on Invoking Batch number {0}: {1}
TimeSpentCollectBatchMessage     = Time spent on Collecting Batch number {0}: {1}
SleepMessage                     = Sleeping for {0} Milliseconds
TerminateJobMessage              = Finishing the {0} job(s) that are still running
NullAuthenticationDetected       = Unable to connect to {0}. Null token detected
MonkeyGenericTaskMessage         = Task [{0}] - Getting {1} from {2}
GraphAPISwitchMessage            = Switching api version to 1.6-internal
MonkeyEmptyResponseMessage       = The {0} query did not return any data in {1} tenant
MonkeyResponseCountMessage       = The query returned {0} elements
SubscriptionWorkingMessage       = Working on {0}
AuthObjectErrorMessage           = Unable to update authentication object for {0}
UserPermissionsMessage           = Getting user permissions for {0}
RBACPermissionErrorMessage       = Unable to get permissions for {0}
RoleBasedPermissionsMessage      = Getting permissions for roleId {0}
RoleBasedGetUsersMessage         = Getting users from roleId {0}
GroupMessageInfo                 = A Group with objectId {0} was found. Getting users
GroupMemberErrorMessage          = Unable to get members for group object {0}
NestedGroupMessageInfo           = Found a group id {0} inside of {1}. Getting users
PotentialNestedGroupDetected     = Potential nested group with name {0} was detected inside of {1}
ResourceGroupsMessage            = Getting resource groups for subscription {0}
ResourceGroupNotFoundMessage     = Resource Group {0} was not found on {1} Azure subscription
AzureUnitResourceMessage         = Getting information from {0} {1}
AzureDatabasesQueryMessage       = Getting databases from {0}
AzureDbThreatDetectionMessage    = Getting Server Threat Detection Policy on {0}
ServerAuditPolicyMessage         = Getting server auditing policy on {0}
DatabaseServerTDEMessage         = Getting Transparent Data Encryption Status on {0}
NoClassicStorageAccounts         = No classic storage accounts were found in {0} tenant
StorageAccountFoundMessage       = Found storage {0} account in {1}
SecurityBaselineENotFoundMessage = Security baseline table was not found for {0}
WorkSpaceIdNotFoundMessage       = Security baseline table was not found for {0}
UnableToCreateQuery              = Unable to create query for {0}
WorkSpaceIdNotFound              = It seems that workspace was not configured for {0} virtual machine
GroupMembersMessage              = Getting group members for {0}
PotentialNestedGroupMessage      = Found a potential nested group name {0} inside of {1}
GroupWithRoleMessage             = Group {0} with a role of {1} was found
SubscriptionResourcesMessage     = Getting resources on {0}
ConvertObjectErrorMessage        = Unable to clone Object
UnableToCreateMonkeyObject       = Unable to create Monkey object
NewFolderMessage                 = New directory created in {0}
UnableToCreateDirectory          = Failed to create new directory on {0}
ExportDataToMessage              = Exporting {0} to {1} format
UnableToExport                   = Unable to export {0} Object to {0} format
SharedAccessUri                  = Getting new Shared Access Uri for {0}
SchemeNotSupported               = Url scheme is not supported. The Url {0} must start with a scheme such as https://
ObjectIdMessageInfo              = Getting {0} information from {1}
EmptyAccessTokensErrorMessage    = Access tokens were not found
StopMonkeyWatcher                = Stopping jobs and access token watcher
MonkeyWatcherAlreadyRunning      = A watcher is already running
RestartMonkeyWatchter            = Restarting monkey watcher
StartMonkeyWatcher               = Starting monkey watcher
MonkeyWatcherStartSuccess        = Monkey watcher has started
MonkeyWatcherErrorMessage        = Monkey watcher has failed
MonkeyWatcherSleepMessage        = Sleeping Monkey watcher before checking access tokens
MonkeyWatcherRefreshTokenMessage = Successfully refreshed token for {0}
ExpiredTokenMessage			     = Access token will expire in {0} minutes. Obtaining a new access token using refresh token
UnableToGetAccessToken           = Unable to get a new access token for {0}
TokenIsStillValidMessage         = Token issued for {0} resource looks good
RefreshTokenMessage              = Refreshing token for {0} using {1} library
NoPsSessionWasFound              = Unable to get {0}. No PsSession was found
O365ATPNotDetected               = Advanced Threat Detection not detected on {0} tenant
O365JobFailedReason              = The reason was {0}
O365JobFailed                    = The job {0} has failed
O365JobError                     = The error was {0}
O365JobCompletedWithError        = Job {0} was completed with errors
O365JobCompleted                 = Job {0} is completed
O365JobCompletedWithoutError     = Job {0} is completed without errors
O365JobStatus                    = Job {0} is still running
ClosingRemoteSession             = Closing remote session to {0}
SecureScoreMessage               = Getting Secure Score from Microsoft Graph
SharepointSubSitesMessage        = Getting subsites for {0}
UnableToSitePropertiesForUser    = Unable to get site properties for {0}
GetSitesUsingSharePointSearchApi = Getting sites using SharePoint search api
UnableToGetSubsites              = Unable to get sub-sites for {0}
UnableToProcessQuery             = Unable to process query on {0}
SPSDetailedErrorMessage          = {0}
SPSCheckSiteForExternalUsers     = Getting external users of site: {0}
SPSCheckSiteAccessRequests       = Getting site access requests of site: {0}
SPSGetListsForWeb                = Getting all lists of site: {0}
SPSGetSharingInfoForItem         = Getting sharing info of {0} item
SPSGetPermissions                = Getting permissions on {0}
SPSScanningMessage               = Getting {0} on {1}
SPSWorkingMessage                = Working on {0} {1}
SPSGetObjectMessage              = Getting {0} on {1}
SPSFolderMessage                 = Working on {0} folder
SPSInheritedPermsMessage         = Getting inherited permissions on {0}
SPSUniquePermsMessage            = Found unique permissions on {0}
LoggerError                      = Unable to start Monkey logger
ReusePortErrorMessage            = Unable to set ReusePort property
AzureSubscriptionNotFound        = No Azure subscription was found on {0}
AzureSubscriptionError           = Azure subscription {0} is expired or cancelled. Subscription status is {1}
ClassicAdminsInfoMessage         = Getting classic administrators from {0}
ClassicAdminsWarningMessage      = Unable to get classic administrators
RoleAssignmentWarningMessage     = Unable to get role assignments from {0} subscription
AzureOrphanedIdentityMessage     = Identity {0} was not found in {1} subscription
UnknownError                     = Unknown error. Probably runspace state was either broken, or closed
RunspaceError                    = Runspace state was not opened
'@;