# Monkey365 - the PowerShell Cloud Security Tool for Azure and Microsoft 365 (copyright 2022) by Juan Garrido
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Function New-MonkeyContainerObject {
<#
        .SYNOPSIS
		Create a new container object

        .DESCRIPTION
		Create a new container object

        .INPUTS

        .OUTPUTS

        .EXAMPLE

        .NOTES
	        Author		: Juan Garrido
            Twitter		: @tr1ana
            File Name	: New-MonkeyContainerObject
            Version     : 1.0

        .LINK
            https://github.com/silverhack/monkey365
    #>

    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseShouldProcessForStateChangingFunctions", "", Scope="Function")]
	[CmdletBinding()]
	Param (
        [parameter(Mandatory= $True, ValueFromPipeline = $True, HelpMessage="Container object")]
        [Object]$InputObject
    )
    Process{
        try{
            #Create ordered dictionary
            $containerObject = [ordered]@{
                id = $InputObject | Select-Object -ExpandProperty id -ErrorAction Ignore;
		        name = $InputObject | Select-Object -ExpandProperty name -ErrorAction Ignore;
                location = $InputObject | Select-Object -ExpandProperty location -ErrorAction Ignore;
		        tags = $InputObject | Select-Object -ExpandProperty tags -ErrorAction Ignore;
                sku = $InputObject.properties | Select-Object -ExpandProperty sku -ErrorAction Ignore;
                type = $InputObject | Select-Object -ExpandProperty type -ErrorAction Ignore;
                identity = $InputObject | Select-Object -ExpandProperty identity -ErrorAction Ignore;
                provisioningState = $InputObject.properties | Select-Object -ExpandProperty provisioningState -ErrorAction Ignore;
                properties = $InputObject | Select-Object -ExpandProperty properties -ErrorAction Ignore;
                encryption = $InputObject.properties | Select-Object -ExpandProperty encryption -ErrorAction Ignore;
                resourceGroupName = $InputObject.Id.Split("/")[4];
                containers = $null;
                networking = [PSCustomObject]@{
                    settings = [PSCustomObject]@{
                        hostName = If($null -ne $InputObject.properties.PsObject.Properties.Item('ipAddress')){$InputObject.properties.ipAddress | Select-Object -ExpandProperty fqdn -ErrorAction Ignore}Else{$null}
                        ports = If($null -ne $InputObject.properties.PsObject.Properties.Item('ipAddress')){$InputObject.properties.ipAddress | Select-Object -ExpandProperty ports -ErrorAction Ignore}Else{$null}
                        dnsNameLabel = If($null -ne $InputObject.properties.PsObject.Properties.Item('ipAddress')){$InputObject.properties.ipAddress | Select-Object -ExpandProperty dnsNameLabel -ErrorAction Ignore}Else{$null}
                        autoGeneratedDomainNameLabelScope = If($null -ne $InputObject.properties.PsObject.Properties.Item('ipAddress')){$InputObject.properties.ipAddress | Select-Object -ExpandProperty autoGeneratedDomainNameLabelScope -ErrorAction Ignore}Else{$null}
                        staticIP = If($null -ne $InputObject.properties.PsObject.Properties.Item('ipAddress')){$InputObject.properties.ipAddress | Select-Object -ExpandProperty ip -ErrorAction Ignore}Else{$null}
                    };
                    publicNetworkAccess = If($null -ne $InputObject.properties.PsObject.Properties.Item('ipAddress')){If($InputObject.properties.ipAddress.type.ToLower() -eq 'public'){$True}Else{$false}}Else{$false}
                    subnetIds = $InputObject.properties | Select-Object -ExpandProperty subnetIds -ErrorAction Ignore
                    virtualNetworkId = $null
                };
                diagnosticSettings = [PSCustomObject]@{
                    enabled = $false;
                    name = $null;
                    id = $null;
                    properties = $null;
                    rawData = $null;
                };
                locks = $null;
                identityRbac = $null;
                rawObject = $InputObject;
            }
            #Create PsObject
            $_obj = New-Object -TypeName PsObject -Property $containerObject
            #return object
            return $_obj
        }
        catch{
            $msg = @{
			    MessageData = ($message.MonkeyObjectCreationFailed -f "Container object");
			    callStack = (Get-PSCallStack | Select-Object -First 1);
			    logLevel = 'error';
			    InformationAction = $O365Object.InformationAction;
			    Tags = @('ContainerObjectError');
		    }
		    Write-Error @msg
            $msg.MessageData = $_
            $msg.LogLevel = "Verbose"
            $msg.Tags+= "ContainerObjectError"
            [void]$msg.Add('verbose',$O365Object.verbose)
		    Write-Verbose @msg
        }
    }
}
